language: node_js
node_js:
- '0.10'
before_script:
- npm install -g karma-cli
env:
  global:
  - secure: Otvgmi5xIG3GsLrAeNk1HDog9s+FUmYBQeaRjjBWxRKIuq57XBAB8LRRPcUuLQMoLm4WssmaaDh+ecD6QIk2McjqlxFQeJ5wyt1RPBQCv3GUBcLkCTZfbbCb5NFfwjl2txhY2gmTzRiwcl4lTaaTSAE+NW9Q59tN1lOaK6nTPog=
  - secure: g0SqKATpeKiJx4R9u/v6YMZq/PNhjPILs9LtX1vvi3B0sU6jAjbLZJeWJ7LbJRj6B8/qz7l/9XmGICvBoZe7lSV65C/JFMsUIGh31KERiSmUFBcYRrHEthxF/rMLng4gyGnnj4mXLq2pNckaSoDj0qQ5fhEzY+HYns7cqhLhah4=
addons:
  sauce_connect: true
